# Generated by Django 3.0.5 on 2020-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200506_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, default='本篇文章暂无摘要', null=True, verbose_name='文章摘要'),
        ),
    ]
