# Generated by Django 3.0.5 on 2020-05-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ststus',
            new_name='status',
        ),
    ]
