# Generated by Django 3.0.5 on 2020-06-10 13:17

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_auto_20200520_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='答案内容'),
        ),
    ]
